config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  get 'about', to: 'pages#about'
  
  resources :articles
  
  get 'signup', to: 'users#new'
  
  post 'users', to: 'users#create'
  resources :users, except: [:new]
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :categories, except: [:destroy]
  
  get 'my_friends', to: 'users#my_friends'
  resources :friendship
  
  get 'search_friends', to: 'users#search'
  
  post 'add_friend', to: 'users#add_friend'
  

end

app/views/friends/_lookup.html.erb
<div id="friend-lookup">
  <h3>Search for friends</h3>
  
  <%= form_tag search_friends_path, remote: true, method: :get, id: 'friend-lookup-form' do %>
    <div class="form-group row no-padding text-center col-md-12">
      <div class="col-md-10">
        
        <%= text_field_tag :search_param, ## here uses search in users_controller
        params[:search_param],
        placeholder: 'Username or Email', autofocus: true, class: 'form-control search-box input-lg' %>
      </div>
      <div class="col-md-2">
        <%= button_tag(type: :submit, class: 'btn btn-lg btn-success') do %>
          <i class='fa fa-search'></i> Look up a friend
        <% end %>
      </div>
    </div>
  <% end %>
  <%= render 'common/spinner' %>
  <% if @users %>
    <% if @users.size > 0 %>
      <h3>Search Results</h3>
      <div id="friend-lookup-results" class="well results-block col-md-10">
        <table class="search-results-table col-md-12">
          <tbody>
            <% @users.each do |user| %>
            <tr>
              <td><strong>Name:</strong> <%= user.username %></td>
              <td><strong>Email:</strong> <%= user.email %></td>
              <td><strong>Profile:</strong> <%= link_to "View Profile", user_path(user), class: "btn btn-xs btn-success" %>
              <% if current_user.not_friends_with?(user.id) %>
                <%= link_to "Add as my friend", add_friend_path(user: current_user, friend: user),
                class: 'btn btn-xs btn-success', method: :post %>
              <% else %>
                <span class='label label-primary'>
                You are friends
                </span>
              <% end %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    <% else %>
      <p class="lead col-md-12">
      No people match this search criteria
      </p>
    <% end %>
  <% end %>
  <div id="friend-lookup-errors"></div>
</div>