config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  get 'about', to: 'pages#about'
  
  resources :articles
  
  get 'signup', to: 'users#new'
  
  post 'users', to: 'users#create'
  resources :users, except: [:new]
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :categories, except: [:destroy]
  
  get 'my_friends', to: 'users#my_friends'
  resources :friendship
  
  get 'search_friends', to: 'users#search'
  
  post 'add_friend', to: 'users#add_friend'
  

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: {minimum: 3, maximum: 50}
  validates :description, presence: true, length: {minimum: 10, maximum: 300}
  validates :user_id, presence: true
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update,:show, :destroy]
  before_action :require_user, except: [:index,:show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  def new
    @article = Article.new
  end
  def index
    @articles = Article.paginate(page: params[:page], per_page:5)
  end
  
  def edit
    
  end
  def create
    #render plain: params[:article].inspect
    
    @article = Article.new(article_params)
    # @article.user = User.first
    @article.user = current_user
    if @article.save
      flash[:success] = "Article was successfully created"
      ## gives user output for confrmation
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end
  def update
    
    if @article.update(article_params)
      flash[:success] = "Article was successfully updated"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end
  
  def show
    
  end
  
  def destroy
     @article.destroy
     flash[:danger] = "Article was successfully deleted"
     redirect_to articles_path
  end
  
  ## from params hash makes article from these two items
  private
  
    def set_article
      @article = Article.find(params[:id])
    end
    def article_params
      params.require(:article).permit(:title,:description, category_ids: [])## category id coem in array form
    end
    
    def require_same_user
      if current_user != @article.user && !current_user.admin? 
        ##if user not article user and not an admin
        flash[:danger] = "You can only edit or delete your own articles"
        redirect_to root_path
      end
      
    end

end

app/views/articles/_article.html.erb
<!--iterate thorugh @articles to display-->
  <% obj.each do |article| %>
    <div class='row'>
      <div class="col-xs-8 col-xs-offset-2">
        <div class="well well-lg">
          <div class="article-title">
            <%= link_to article.title, article_path(article) %>
          </div>
          <div class="article-body">
            <%= truncate(article.description, length: 100) %><!-- truncates art desc -->
            <div class="article-meta-details">
              <small>Created by: <%= article.user.username if article.user %>, <!-- if exists -->
              <%= time_ago_in_words(article.created_at) %> ago,
              last updated: <%= time_ago_in_words(article.updated_at) %> ago</small>
            </div>
            
          </div>
          <% if article.categories.any? %>
            <p>Categories: <%= render article.categories %></p>
          <% end %>
          <% if logged_in? && (current_user == article.user || current_user.admin?) %>
            <div class="article-actions">
              <%= link_to "Edit this article", edit_article_path(article), class: 
              "btn btn-xs btn-primary"%>
              <%= link_to "Delete this article", article_path(article), method: :delete, 
                                                  data: {confirm: "Are you sure you want to delete this article?"}, 
                                                  class: "btn btn-xs btn-danger" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    
  <% end %>

app/views/articles/_form.html.erb
<%= render "partials/errors", obj: @article %>

<div class='row'>
  <div class='col-md-12'>
  
  <!-- form_for for autogeneratin html forms code -->
  <%= form_for(@article, :html =>{class: "form-horizontal", role: "form"}) do |f| %>
    <div class='form-group'>
      <div class='control-label col-sm-2'>

        <%= f.label :title %>
      </div>
      <div class='col-sm-8'>
        <%= f.text_field :title ,class:'form-control',placeholder: "Title of Article", autofocus: true %>
      </div>
    </div>
    <div class='form-group'>
      <div class='control-label col-sm-2'>
        <%= f.label :description %><br>
      </div>
      <div class='col-sm-8'>
        <%= f.text_area :description, rows: 10, class:'form-control',placeholder: "Body of Article", autofocus: true %>
      </div>
    </div>
    <div class="form-group">
      <div class="row">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %><!-- make checkbox for all category options -->
            <%= cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
            <!-- name of category right after checkbox -->
          <% end %>
        </div>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit class: 'btn btn-primary btn-lg' %>
      </div>
    </div>
  <% end %>
  <div class="col-xs-4 col-xs-offset-5">
    [<%= link_to "Cancel request and return to articles listing", articles_path %>]
  </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h2 align="center">Edit an existing article here</h2>

<%= render "form" %>

app/views/articles/index.html.erb
<h1 align="center">List of all articles</h1>

<div align="center">
  <%= will_paginate %>
</div>
<%= render 'article',obj: @articles %>
<div align="center">
  <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1 align="center">Create an article</h1>
<%= render "form" %>

app/views/articles/show.html.erb
<h2 align="center">Title: <%= @article.title%></h2>
<div class="well col-xs-8 col-xs-offset-2">
  <% if @article.user %>
    <ul class="listing">
        <div class="row" align="center">
          <div class="col-md-4 col-md-offset-4">
            <li>Created by:</li>
            <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
            <li class="article-title">
              <%= link_to @article.user.username, user_path(@article.user)%>
            </li>
            <li><small><%=pluralize(@article.user.articles.count, "article") if @article.user.articles %></small></li>
          </div>
        </div>
      </ul>
  <% end %>
  <h4 align="center" class="description"><strong>Description:</strong></h4>
  <hr>
  <%= simple_format(@article.description) %>
  <% if @article.categories.any? %>
    <p>Categories: <%= render @article.categories %></p>
  <% end %>
  <div class="article-actions">
    <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
      <%= link_to "Edit this article", edit_article_path(@article), class: 
      "btn btn-xs btn-primary"%>
      <%= link_to "Delete this article", article_path(@article), method: :delete, 
                                          data: {confirm: "Are you sure you want to delete this article?"}, 
                                          class: "btn btn-xs btn-danger" %>
    <% end %>
    <%= link_to "View all articles", articles_path, class: "btn btn-xs btn-success" %>
  </div>
</div>