config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  get 'about', to: 'pages#about'
  
  resources :articles
  
  get 'signup', to: 'users#new'
  
  post 'users', to: 'users#create'
  resources :users, except: [:new]
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :categories, except: [:destroy]
  
  get 'my_friends', to: 'users#my_friends'
  resources :friendship
  
  get 'search_friends', to: 'users#search'
  
  post 'add_friend', to: 'users#add_friend'
  

end

app/views/partials/_errors.html.erb
<% if obj.errors.any? %>
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <div class="panel panel-danger">
      <div class="panel-heading">
        <h2 class="panel-title">
          <%= pluralize(obj.errors.count, "error") %><!-- shows errors in ruby code -->
          prohibited this particle from being saved:
        </h2>
        <div class="panel-body">
          <ul>
            <% obj.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/partials/_footer.html.erb
<footer>
    Crafted with &hearts; in Burnaby by <a href="">James</a>
</footer>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar navbar-inverse">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <!-- embeded ruby for link with calsses and id -->
            <%= link_to "alphaBlog", root_path, class: "navbar-brand", id: "logo" %>
        </div>
        <div class="collapse navbar-collapse" id="navbar-collapse">
            <ul class="nav navbar-nav navbar-left">
                <li><%= link_to "Home", root_path %></li>
                <li><%= link_to "About", about_path %></li>
                <li><%= link_to "Articles", articles_path %></li>
                <li><%= link_to "Users", users_path %></li><!-- restrict only for logged in users -->
                
                <% if logged_in? %>
                    <li><%= link_to "Friends", my_friends_path %></li>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
                      <ul class="dropdown-menu">
                          <li><%= link_to "first actionEdit your profile", "#" %></li>
                          <li><%= link_to 'another action', "#" %></li>
                          <li><%= link_to "New Article", new_article_path %></li>
                          
                      </ul>
                    </li>
                
                <% end %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                      <li><%= link_to "All categories", categories_path %></li>
                      <% Category.all.each do |category| %>
                          <li><%= link_to "#{category.name}", category_path(category) %></li>
                      <% end %>
                      <% if logged_in? and current_user.admin? %>
                          <li role="separator" class="divider"></li>
                          <li><%= link_to "Create New Category", new_category_path %></li>
                      <% end %>
                  </ul>
                </li>
            
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <% if logged_in? %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Profile <%= "Admin" if current_user.admin? %><span class="caret"></span></a>
                  <ul class="dropdown-menu">
                      <li><%= link_to "Edit your profile", edit_user_path(current_user) %></li>
                      <li><%= link_to 'View your profile', user_path(current_user) %></li>
                      <li><%= link_to "New Article", new_article_path %></li>
                        
                  </ul>
                </li>
                <li><%= link_to "Log out", logout_path, method: :delete %></li><!-- since destory action, must give method delte -->
                <% else %>
                    <li><%= link_to "Login", login_path %></li>
                    <li><%= link_to "Sign up", signup_path %></li>
                <% end %>
                
            </ul>
        </div>
    </div>
</nav>
<div class="row">
    <div class="col-xs-10 col-xs-offset-1">
        <% flash.each do |name, msg| %>
            <div class='alert alert-<%= "#{name}" %>'>
                <a href="#" class="close" data-dismiss="alert">&#215;</a>
                <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
            </div>
          
        <% end %>
    </div>
</div>